# Generated by Django 5.2.5 on 2025-09-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Roupa')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('categoria', models.CharField(choices=[('tops', 'Tops'), ('leggings', 'Leggings'), ('conjuntos', 'Conjuntos'), ('blusas', 'Blusas'), ('calcinha-sem-costura', 'Calcinha Sem Costura'), ('meias', 'Meias'), ('acessorios', 'Acessórios')], max_length=50, verbose_name='Categoria')),
                ('tamanhos_disponiveis', models.CharField(default='P,M,G', max_length=20, verbose_name='Tamanhos Disponíveis')),
                ('foto_principal', models.ImageField(upload_to='roupas/', verbose_name='Foto Principal')),
                ('foto_2', models.ImageField(blank=True, null=True, upload_to='roupas/', verbose_name='Foto 2')),
                ('foto_3', models.ImageField(blank=True, null=True, upload_to='roupas/', verbose_name='Foto 3')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Roupa',
                'verbose_name_plural': 'Roupas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
