# Generated by Django 5.2.5 on 2025-01-27 00:00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Roupa')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('tamanhos_disponiveis', models.CharField(default='P,M,G', max_length=20, verbose_name='Tamanhos Disponíveis')),
                ('foto_principal', models.URLField(max_length=500, verbose_name='URL da Foto Principal')),
                ('foto_principal_storage_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caminho no Storage')),
                ('foto_2', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Foto 2')),
                ('foto_2_storage_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caminho no Storage 2')),
                ('foto_3', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Foto 3')),
                ('foto_3_storage_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caminho no Storage 3')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Roupa',
                'verbose_name_plural': 'Roupas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]