# Generated by Django 5.2.5 on 2025-09-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='foto_2',
            field=models.BinaryField(blank=True, null=True, verbose_name='Foto 2 (WebP)'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='foto_3',
            field=models.BinaryField(blank=True, null=True, verbose_name='Foto 3 (WebP)'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='foto_principal',
            field=models.BinaryField(verbose_name='Foto Principal (WebP)'),
        ),
    ]
