# Generated by Django 5.2.5 on 2025-09-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_roupa_foto_2_alter_roupa_foto_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='categoria',
            field=models.CharField(choices=[('tops', 'Tops'), ('leggings', 'Leggings'), ('conjuntos', 'Conjuntos'), ('blusas', 'Blusas'), ('acessorios', 'Acessórios'), ('macacao', 'Macacão'), ('macaquinho', 'Macaquinho'), ('short', 'Short'), ('regata', 'Regata')], max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to='roupas/', verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='foto_3',
            field=models.ImageField(blank=True, null=True, upload_to='roupas/', verbose_name='Foto 3'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='foto_principal',
            field=models.ImageField(upload_to='roupas/', verbose_name='Foto Principal'),
        ),
    ]
