# Generated by Django 5.2.5 on 2025-09-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_roupa_foto_2_alter_roupa_foto_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='categoria',
            field=models.CharField(choices=[('tops', 'Tops'), ('leggings', 'Leggings'), ('conjuntos', 'Conjuntos'), ('blusas', 'Blusas'), ('calcinha-sem-costura', 'Calcinha Sem Costura')], max_length=50, verbose_name='Categoria'),
        ),
    ]
