# Generated by Django 5.2.5 on 2025-09-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_roupa_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='categoria',
            field=models.CharField(choices=[('tops', 'Tops'), ('leggings', 'Leggings'), ('conjuntos', 'Conjuntos'), ('blusas', 'Blusas'), ('acessorios', 'Acessórios'), ('macacao', 'Macacão'), ('macaquinho', 'Macaquinho'), ('short', 'Short'), ('regata', 'Regata')], max_length=50, verbose_name='Categoria'),
        ),
    ]
