# Generated by Django 5.2.5 on 2025-09-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_roupa_foto_2_storage_path_roupa_foto_3_storage_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roupa',
            name='foto_2_storage_path',
        ),
        migrations.RemoveField(
            model_name='roupa',
            name='foto_3_storage_path',
        ),
        migrations.RemoveField(
            model_name='roupa',
            name='foto_principal_storage_path',
        ),
        migrations.AlterField(
            model_name='roupa',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to='roupas/', verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='foto_3',
            field=models.ImageField(blank=True, null=True, upload_to='roupas/', verbose_name='Foto 3'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='foto_principal',
            field=models.ImageField(upload_to='roupas/', verbose_name='Foto Principal'),
        ),
    ]
