# Generated by Django 5.2.5 on 2025-09-11 11:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_roupa_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='foto_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='foto_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto 3'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='foto_principal',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Foto Principal'),
        ),
    ]
