# Generated by Django 5.2.5 on 2025-09-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_remove_roupa_foto_2_storage_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='foto_2_storage_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caminho no Storage 2'),
        ),
        migrations.AddField(
            model_name='roupa',
            name='foto_3_storage_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caminho no Storage 3'),
        ),
        migrations.AddField(
            model_name='roupa',
            name='foto_principal_storage_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caminho no Storage'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='foto_2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Foto 2'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='foto_3',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Foto 3'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='foto_principal',
            field=models.URLField(max_length=500, verbose_name='URL da Foto Principal'),
        ),
    ]
