services:
  - type: web
    name: lmfit
    env: python
    plan: free
    buildCommand: "chmod +x deploy.sh && ./deploy.sh"
    startCommand: "gunicorn LMFIT.wsgi:application --settings=LMFIT.production_settings"
    envVars:
      - key: DEBUG
        value: False
      - key: RENDER
        value: True
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        value: roupas