services:
  - type: web
    name: lmfit
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate --settings=LMFIT.production_settings && python manage.py collectstatic --noinput --settings=LMFIT.production_settings && python manage.py setup_admin --settings=LMFIT.production_settings"
    startCommand: "gunicorn LMFIT.wsgi:application --settings=LMFIT.production_settings"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        value: roupas
      - key: SUPABASE_DB_HOST
        sync: false
      - key: SUPABASE_DB_NAME
        value: postgres
      - key: SUPABASE_DB_USER
        value: postgres
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: SUPABASE_DB_PORT
        value: "5432"